import { handleActions, createAction } from 'redux-actions'

const SIGN_IN_EMAIL_REQUEST = 'SIGN_IN_EMAIL_REQUEST';
const SIGN_IN_EMAIL_SUCCESS = 'SIGN_IN_EMAIL_SUCCESS';
const SIGN_IN_EMAIL_FAILED = 'SIGN_IN_EMAIL_FAILED';

const SIGN_IN_GOOGLE_REQUEST = 'SIGN_IN_GOOGLE_REQUEST';
const SIGN_IN_GOOGLE_SUCCESS = 'SIGN_IN_GOOGLE_SUCCESS';
const SIGN_IN_GOOGLE_FAILED = 'SIGN_IN_GOOGLE_FAILED';

const SIGN_IN_FACEBOOK_REQUEST = 'SIGN_IN_FACEBOOK_REQUEST';
const SIGN_IN_FACEBOOK_SUCCESS = 'SIGN_IN_FACEBOOK_SUCCESS';
const SIGN_IN_FACEBOOK_FAILED = 'SIGN_IN_FACEBOOK_FAILED';

const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_REQUEST';
const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';